### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by emilytoppm** [wagtail/docker-wagtail-develop#5]
This all looks great! I just wanted to bring up a minor issue - namely that on my machine at least, the naming of the containers is inconsistent with the readme.

On my machine, they show as `dockerwagtaildevelop_web_1`, whereas in the readme they're written as `docker-wagtail-develop_web_1`. Very minor issue, and of course happy to submit a PR to fix typos, but just checking whether this is in fact inconsistent between machines, and if so whether that should be standardised?

**Comment by saevarom** [comment]
This could be due to different versions of Docker perhaps? What is your version of Docker / Docker compose?

I'm running 
- Docker engine: 19.03.05
- Compose: 1.25.2


We could perhaps add a note to the README saying that output may vary depending on local software versions?

**Comment by saevarom** [comment]
Actually, I think we can change to not rely on the `docker` command, but `docker-compose` instead.

That way we can refer to containers by their service name, e.g.

`docker-compose exec web python manage.py shell_plus`

instead of 

`docker exec -it docker-wagtail-develop_web_1 python manage.py shell`

**Comment by saevarom** [comment]
Fixed in #6
